#!/usr/bin/env bash
#MISE description="Build the project"
#MISE depends=["setup"]
#MISE sources=["src/**/*"]
#MISE outputs=["dist/index.js"]

bun build ./src/index.ts --outdir dist --target bun
cp -r scripts dist/
